/*
 * stm32f401xx_i2c_driver.c
 *
 *  Created on: 05-Jun-2026
 *      Author: TGT
 */

#include "stm32f401xx.h"

//helper function prototypes
static void I2C_GenerateStartCondition(I2C_Reg_Def_t *pI2Cx);
static void I2C_ExecuteAddressPhase(I2C_Reg_Def_t *pI2Cx,uint8_t Addr,uint8_t WorR);
static void I2C_ClearAddrFlag(I2C_Handle_t *pI2CHandle);
static void I2C_GenerateStopCondition(I2C_Reg_Def_t *pI2Cx);
static void I2C_MasterHandleRXNEInterrupt(I2C_Handle_t *pI2CHandle);
static void I2C_MasterHandleTXEInterrupt(I2C_Handle_t *pI2CHandle);


#define I2C_WRITE	0
#define I2C_READ	1




/* PERIPHERAL CLOCK SETUP*/
/*********************************************************************
 * @fn      		  - I2C_PeriClockControl
 *
 * @brief             - This function enables or disables peripheral clock for the given I2C port
 *
 * @param[in]         - base address of the I2C peripheral
 * @param[in]         - ENABLE or DISABLE macros
 * @param[in]         -
 *
 * @return            -  none
 *
 * @Note              -  none

 */


void I2C_PeriClockControl(I2C_Reg_Def_t *pI2Cx,uint8_t EnorDi)
{
	if(EnorDi == ENABLE)
	{
		if(pI2Cx == I2C1)
		{
			I2C1_PCLK_EN();
		}
		else if(pI2Cx == I2C2)
		{
			I2C2_PCLK_EN();
		}
		else if(pI2Cx == I2C3)
		{
			I2C3_PCLK_EN();
		}

	}
	else
	{
		if(pI2Cx == I2C1)
		{
			I2C1_PCLK_DI();
		}
		else if(pI2Cx == I2C2)
		{
			I2C2_PCLK_DI();
		}
		else if(pI2Cx == I2C3)
		{
			I2C3_PCLK_DI();
		}

	}


}


uint16_t AHB_PreScaler[8] = {2,4,8,16,64,128,256,512};
uint16_t APB_PreScaler[4] = {2,4,8,16};

uint32_t RCC_GetPCLK1Value(void)
{
	uint32_t pclk,SystemClk;
	uint8_t clksrc,temp,apb1p;
	uint16_t ahbp;
	clksrc = (RCC->CFGR>>2)&0x3;

	if(clksrc == 0)
	{
		SystemClk = 16000000;
	}

	temp = (RCC->CFGR>>4)&0xF;

	if(temp<8)
	{
		ahbp =1;
	}
	else
	{
		ahbp = AHB_PreScaler[temp-8];
	}

	temp = (RCC->CFGR>>10)&0x7;

	if(temp<4)
	{
		apb1p =1;
	}
	else
	{
		apb1p = APB_PreScaler[temp-4];
	}

	pclk = SystemClk/(ahbp*apb1p);

	return pclk;


}








//I2C INIT AND DEINIT API IMPLEMENTATION



void I2C_Init(I2C_Handle_t *pI2CHandle)
{


	uint32_t tempreg = 0;

	//ack control bit
	tempreg |= pI2CHandle-> I2C_Config.I2C_ACKControl<<10;
	pI2CHandle->pI2Cx->CR1 = tempreg;


	//configure the FREQ field of CR2
	tempreg = 0;
	tempreg	|= (RCC_GetPCLK1Value()/1000000U)&0x3F;
	pI2CHandle->pI2Cx->CR2 = tempreg;

	//program device own address
	tempreg =  pI2CHandle->I2C_Config.I2CDeviceAddress<<1;
	tempreg = 1<<14;
	pI2CHandle->pI2Cx->OAR1 = tempreg;

	//ccr values
	uint16_t  ccr_value  = 0;
	tempreg = 0;
	if(pI2CHandle->I2C_Config.I2CSCLSpeed <= I2C_SCL_SPEED_SM)
	{
		// MODE IS STANDARD MODE
		ccr_value = RCC_GetPCLK1Value()/(2*(pI2CHandle->I2C_Config.I2CSCLSpeed));
		tempreg |= (ccr_value & 0xFFF);
	}
	else
	{
		//mode is fast mode
		tempreg |= 1<<15;
		tempreg |= pI2CHandle->I2C_Config.I2C_FMDutyCycle <<14;
		if(pI2CHandle->I2C_Config.I2C_FMDutyCycle == I2C_FM_DUTY_2)
		{
			ccr_value = RCC_GetPCLK1Value()/(3*pI2CHandle->I2C_Config.I2CSCLSpeed);
		}
		else
		{
			ccr_value = RCC_GetPCLK1Value()/(25*pI2CHandle->I2C_Config.I2CSCLSpeed);
		}

		tempreg |=	(ccr_value & 0xFFF);

		pI2CHandle->pI2Cx->CCR |= tempreg;

	}

	//TRISE CONFIGURATION
	if(pI2CHandle->I2C_Config.I2CSCLSpeed <= I2C_SCL_SPEED_SM)
	{
		//standard mode
		tempreg = (RCC_GetPCLK1Value()/1000000U) +1;
	}
	else
	{
		//fast mode
		tempreg = ((RCC_GetPCLK1Value()*300)/1000000000U) +1;
	}
	pI2CHandle->pI2Cx->TRISE |=(tempreg&0x3F);








}

void I2C_DeInit(I2C_Reg_Def_t *pI2Cx)
{

			if(pI2Cx == I2C1)
			{
				I2C1_REG_RESET();
			}
			else if(pI2Cx == I2C2)
			{
				I2C2_REG_RESET();
			}
			else if(pI2Cx == I2C3)
			{
				I2C3_REG_RESET();
			}



}

//send and recieve data apis

void I2C_MasterSendData(I2C_Handle_t *pI2CHandle,uint8_t *pTxBuffer, uint32_t Len, uint8_t SlaveAddr)
{
	//Gnerate the start condition
	I2C_GenerateStartCondition(pI2CHandle->pI2Cx);

	//confirm that the start condition is generated by checking the sb flag in sr1
	//note: until sb is cleared scl is pulled to low
	while(!(pI2CHandle->pI2Cx->SR1&0x1));

	// send address of the slave with r/nw bit set to w(0) (total 8 bits)
	I2C_ExecuteAddressPhase(pI2CHandle->pI2Cx,SlaveAddr,I2C_WRITE);

	//confirm that address phase is completed by checking the ADDR flag in SR1
	while(!(pI2CHandle->pI2Cx->SR1&0x2));

	//clear the addr flag according to its software sequence
	//NOTE: until addr is scl will be stretched
	I2C_ClearAddrFlag(pI2CHandle);

	//send the data until len becomes 0
	while(Len > 0)
	{
		while(!((pI2CHandle->pI2Cx->SR1>>7)&0x1));
		pI2CHandle->pI2Cx->DR = *pTxBuffer;
		pTxBuffer++;
		Len--;
	}

	//When len becomes 0 wait for txe =1 and btf =1 before generating stop condition
	//note: txe =1 and btf =1 means both sr and dr are empty and next tx should begin
	//when btf =1 scl is pulled to low
	//wait till txe set
	while(!((pI2CHandle->pI2Cx->SR1>>7)&0x1));
	//wait till btf is set
	while(!((pI2CHandle->pI2Cx->SR1>>2)&0x1));


	//generate stop condition and master need not to wait for completion of stop condition
	//note: generating stop , automatically clears the btf
	I2C_GenerateStopCondition(pI2CHandle->pI2Cx);


}

void I2C_MasterRecieveData(I2C_Handle_t *pI2CHandle,uint8_t *pRxBuffer, uint32_t Len, uint8_t SlaveAddr)
{
	// Generate the start condition
	I2C_GenerateStartCondition(pI2CHandle->pI2Cx);


	//confirm that the start generation completed by checking the SB flag in SR1
	//until SB IS Cleared scl is pulled to gnd
	while(!(pI2CHandle->pI2Cx->SR1&0x1));

	//send the address of slave with r/nw set to 1
	I2C_ExecuteAddressPhase(pI2CHandle->pI2Cx, SlaveAddr, I2C_READ);


	// wait until addr phase is completed by checking the addr flag in SR1
	while(!(pI2CHandle->pI2Cx->SR1&0x2));

	//procedure to read 1 byte data from slave
	if(Len ==1)
	{
		//Disable Acking
		pI2CHandle->pI2Cx->CR1	&= ~(1<<10);

		//clear the addr flag
		I2C_ClearAddrFlag(pI2CHandle);

		//wait until rxne becomes 1
		while(!((pI2CHandle->pI2Cx->SR1>>6)&0x1));

		//generate stop condition
		I2C_GenerateStopCondition(pI2CHandle->pI2Cx);

		//read data into buffer
		*pRxBuffer = pI2CHandle->pI2Cx->DR;

		//set the ack bit
		pI2CHandle->pI2Cx->CR1	|= (1<<10);

		return;

	}

	if(Len>1)
	{
		//clear the addr flag
		I2C_ClearAddrFlag(pI2CHandle);

		//read the data until len becomes zero
		while(Len >0)
		{
			//WAIT UNTIL RXNE BECOMES 1
			while(!((pI2CHandle->pI2Cx->SR1>>6)&0x1));

			if(Len==2)
			{
				//wait until btf is set
				while(!((pI2CHandle->pI2Cx->SR1>>2)&0x1));

				//clear the ack bit
				pI2CHandle->pI2Cx->CR1	&= ~(1<<10);

				//generate stop condition
				I2C_GenerateStopCondition(pI2CHandle->pI2Cx);

			}

			//read the data from data register in to buffer
			*pRxBuffer = pI2CHandle->pI2Cx->DR;
			Len--;
			//increment the buffer address
			pRxBuffer++;



		}
	}
	// re- enable acking
	pI2CHandle->pI2Cx->CR1	|= (1<<10);




}


void I2C_SlaveSendData(I2C_Reg_Def_t *pI2Cx,uint8_t Data)
{
	(pI2Cx->DR) = Data;

}
uint8_t I2C_SlaveRecieveData(I2C_Reg_Def_t *pI2Cx)
{
	return (uint8_t)(pI2Cx->DR);
}






//helper functions


static void I2C_GenerateStartCondition(I2C_Reg_Def_t *pI2Cx)
{
	pI2Cx->CR1	|= (1<<8);



}

static void I2C_ExecuteAddressPhase(I2C_Reg_Def_t *pI2Cx,uint8_t Addr,uint8_t WorR)
{
	Addr = Addr<<1;
	if(WorR==I2C_WRITE)
	{
		Addr &= ~(1);
	}
	else
	{
		Addr |=1;
	}
	pI2Cx->DR = Addr;
}

static void I2C_ClearAddrFlag(I2C_Handle_t *pI2CHandle)
{
	uint32_t dummyread;
	//check for device mode
	if(pI2CHandle->pI2Cx->SR2&(0x1))
	{
		//device is in master mode
		if(pI2CHandle->TxRxState==I2C_BUSY_IN_RX)
		{
			if(pI2CHandle->RxSize==1)
			{
				//first disable the ack
				pI2CHandle->pI2Cx->CR1 &= ~(1<<10);

			}
		//clear the addr flag (read sr1 and sr2)
		dummyread = pI2CHandle->pI2Cx->SR1;
		dummyread = pI2CHandle->pI2Cx->SR1;
		(void)dummyread;

		}
		else
		{
			//clear the addr flag (read sr1 and sr2)
			dummyread = pI2CHandle->pI2Cx->SR1;
			dummyread = pI2CHandle->pI2Cx->SR1;
			(void)dummyread;


		}
	}
	else
	{
		//device in slave mode
		//clear the addr flag (read sr1 and sr2)
		dummyread = pI2CHandle->pI2Cx->SR1;
		dummyread = pI2CHandle->pI2Cx->SR1;
		(void)dummyread;
	}


}
static void I2C_GenerateStopCondition(I2C_Reg_Def_t *pI2Cx)
{
	pI2Cx->CR1	|= (1<<9);



}


/*********************************************************************
 * @fn      		  - I2C_IRQConfig
 *
 * @brief             - interrupt request configuration of that I2C port
 *
 * @param[in]         - irq number of that interrupt
 * @param[in]         - priority number of that interrupt
 * @param[in]         - enable or disable macros
 *
 * @return            -  none
 *
 * @Note              -  none

 */

void I2C_IRQInterruptConfig(uint8_t IRQNumber, uint8_t EnorDi)
{

	if(EnorDi == ENABLE)
	{
	if(IRQNumber <= 31)
	{
		//program iser0 register
		*NVIC_ISER0 |= (1 << IRQNumber);
	}
	else if (IRQNumber >31 && IRQNumber <64)
	{
		//program iser1 register
		*NVIC_ISER1 |= (1 << (IRQNumber%32));

	}
	else if(IRQNumber >= 64 && IRQNumber < 96)
	{
		//program iser2 register
		*NVIC_ISER2 |= (1 << (IRQNumber%64));
	}
	}

	else
	{

		if(IRQNumber <= 31)
			{
				//program icer0 register
			*NVIC_ICER0 |= (1 << IRQNumber);

			}
			else if (IRQNumber >31 && IRQNumber <64)
			{
				//program icer1 register
				*NVIC_ICER1 |= (1 << (IRQNumber%32));
			}
			else if(IRQNumber >= 64 && IRQNumber < 96)
			{
				//program icer2 register
				*NVIC_ICER2 |= (1 << (IRQNumber%64));
			}

	}

}


void  I2C_IRQPriorityConfig(uint8_t IRQNumber,uint32_t Priority )
{
	// first lets find out priority register
	uint8_t iprx = IRQNumber/4;
	uint8_t iprx_section = IRQNumber %4;

	*(NVIC_PR_BASE_ADDR +(iprx)) |= (Priority << (8*iprx_section+4)); // FOR ARM CROTEX M4 ONLY AS LOWER 4 BITS ARE NOT APPLICABLE


}

/*********************************************************************
 * @fn      		  - I2C_MasterSendDataIT
 *
 * @brief             -
 *
 * @param[in]         -
 * @param[in]         -
 * @param[in]         -
 *
 * @return            -
 *
 * @Note              -  Complete the below code . Also include the function prototype in header file

 */
uint8_t  I2C_MasterSendDataIT(I2C_Handle_t *pI2CHandle,uint8_t *pTxBuffer, uint32_t Len,uint8_t SlaveAddr,uint8_t Sr)
{

	uint8_t busystate = pI2CHandle->TxRxState;

	if( (busystate != I2C_BUSY_IN_TX) && (busystate != I2C_BUSY_IN_RX))
	{
		pI2CHandle->pTxBuffer = pTxBuffer;
		pI2CHandle->TxLen = Len;
		pI2CHandle->TxRxState = I2C_BUSY_IN_TX;
		pI2CHandle->DevAddr = SlaveAddr;
		pI2CHandle->Sr = Sr;

		//Implement code to Generate START Condition
		I2C_GenerateStartCondition(pI2CHandle->pI2Cx);

		//Implement the code to enable ITBUFEN Control Bit
		pI2CHandle->pI2Cx->CR2 |= ( 1 << 10);

		//Implement the code to enable ITEVFEN Control Bit
		pI2CHandle->pI2Cx->CR2 |= ( 1 << 9);

		//Implement the code to enable ITERREN Control Bit
		pI2CHandle->pI2Cx->CR2 |= ( 1 << 8);




	}

	return busystate;

}

/*********************************************************************
 * @fn      		  - I2C_MasterReceiveDataIT
 *
 * @brief             -
 *
 * @param[in]         -
 * @param[in]         -
 * @param[in]         -
 *
 * @return            -
 *
 * @Note              - Complete the below code . Also include the fn prototype in header file

 */
uint8_t I2C_MasterReceiveDataIT(I2C_Handle_t *pI2CHandle,uint8_t *pRxBuffer, uint32_t Len, uint8_t SlaveAddr,uint8_t Sr)
{

	uint8_t busystate = pI2CHandle->TxRxState;

	if( (busystate != I2C_BUSY_IN_TX) && (busystate != I2C_BUSY_IN_RX))
	{
		pI2CHandle->pRxBuffer = pRxBuffer;
		pI2CHandle->RxLen = Len;
		pI2CHandle->TxRxState = I2C_BUSY_IN_RX;
		pI2CHandle->RxSize = Len; //Rxsize is used in the ISR code to manage the data reception
		pI2CHandle->DevAddr = SlaveAddr;
		pI2CHandle->Sr = Sr;

		//Implement code to Generate START Condition
		I2C_GenerateStartCondition(pI2CHandle->pI2Cx);


		//Implement the code to enable ITBUFEN Control Bit
		pI2CHandle->pI2Cx->CR2 |= ( 1 << 10);


		//Implement the code to enable ITEVFEN Control Bit
		pI2CHandle->pI2Cx->CR2 |= ( 1 << 9);


		//Implement the code to enable ITERREN Control Bit
		pI2CHandle->pI2Cx->CR2 |= ( 1 << 8);
	}


	return busystate;
}

void I2C_EV_IRQHandling(I2C_Handle_t *pI2CHandle)
{
	//Interrupt handling for both master and slave mode of a device
	uint32_t temp1,temp2,temp3;

	temp1	= pI2CHandle->pI2Cx->CR2&(1<<9);
	temp2	= pI2CHandle->pI2Cx->CR2&(1<<10);

	//1. handle for interrupt generated  by SB event
	// SB only applicable in Master mode
	temp3 	= pI2CHandle->pI2Cx->SR1&(1);

	if(temp1&&temp2)
	{
		//SB flag is set
		//execution of ADDRESS PHASE

		if(pI2CHandle->TxRxState == I2C_BUSY_IN_TX)
		{
			I2C_ExecuteAddressPhase(pI2CHandle->pI2Cx, pI2CHandle->DevAddr, I2C_WRITE);
		}
		else if(pI2CHandle->TxRxState == I2C_BUSY_IN_RX)
		{
			I2C_ExecuteAddressPhase(pI2CHandle->pI2Cx, pI2CHandle->DevAddr, I2C_READ);

		}

	}


	//2.Handle for interrupt generated by ADDR event
	// in master mode when address is sent
	// in slave mode when address is matched
	temp3 = pI2CHandle->pI2Cx->SR2&(1<<1);

	if(temp1&&temp2)
	{
		//ADDR FLAG IS SET

		I2C_ClearAddrFlag(pI2CHandle);
	}

	//3.Handle for event generated by BTF  event
	temp3 = pI2CHandle->pI2Cx->SR2&(1<<2);

	if(temp1&&temp3)
	{
		//BTF FLAG IS SET
		if(pI2CHandle->TxRxState == I2C_BUSY_IN_TX)
		{
			if(pI2CHandle->pI2Cx->SR1&(1<<7))
			{
				// both BTF and TXE set

				if(pI2CHandle->TxLen==0)
				{
				//1. generate stop condition
					if(pI2CHandle->Sr == I2C_DISABLE_SR)
					{I2C_GenerateStopCondition(pI2CHandle->pI2Cx);}

					//2. reset all member elements of the handle structure
					I2C_CloseSendData(pI2CHandle);

					//3. notify the application  about tx complete
					I2C_ApplicationEventCallback(pI2CHandle, I2C_EV_TX_CMPLT);
					}


			}
		}
	}

	//4. Handle for event generated by STOPF event
	// only valid in slave mode
	temp3 = pI2CHandle->pI2Cx->SR2&(1<<4);

	if(temp1&&temp3)
	{
		//STOPF FLAG IS SET
		//cleared by reading SR1 and then CR1
		pI2CHandle->pI2Cx->CR1 |=0x0000;

		//notify the application that stop is generated by the master
		I2C_ApplicationEventCallback(pI2CHandle,I2C_EV_STOP);
	}

	//5. Handle for event generated by TXE event
	temp3 = pI2CHandle->pI2Cx->SR2&(1<<7);

	if(temp1&&temp3&&temp2)
	{
		//check for device mode
		if(pI2CHandle->pI2Cx->SR2&(1<<0))
		{
		//TXE FLAG IS SET
		//WE HAVE TO DO THE DATA TRANSMISSION
		if(pI2CHandle->TxRxState == I2C_BUSY_IN_TX)
		{
			I2C_MasterHandleTXEInterrupt(pI2CHandle);
		}
		}
		else
		{
			//slave
			//make sure slave is in tx mode
			if(pI2CHandle->pI2Cx->SR2&(1<<3))
			{
				I2C_ApplicationEventCallback(pI2CHandle, I2C_EV_DATA_REQ);
			}
		}
	}

	//5. Handle for event generated by TXE event
	temp3 = pI2CHandle->pI2Cx->SR2&(1<<6);

	if(temp1&&temp3&&temp2)
	{
		//check if device master
		if(pI2CHandle->pI2Cx->SR2&(1<<0))
		{
		//RXXE FLAG IS SET
		//WE HAVE TO DO THE DATA TRANSMISSION
		if(pI2CHandle->TxRxState == I2C_BUSY_IN_RX)
		{
			I2C_MasterHandleRXNEInterrupt(pI2CHandle);
		}
		}
		else
		{
			//slave
			//make sure the slave in rx mode
			if(!(pI2CHandle->pI2Cx->SR2&(1<<3)))
			{
				I2C_ApplicationEventCallback(pI2CHandle, I2C_EV_DATA_RCV);
			}


		}




	}
}


static void I2C_MasterHandleRXNEInterrupt(I2C_Handle_t *pI2CHandle)
{
	// WE HAVE TO DO DATA RECEPTION
	if(pI2CHandle->RxSize==1)
	{
		*pI2CHandle->pRxBuffer = pI2CHandle->pI2Cx->DR;
		pI2CHandle->pRxBuffer++;
		pI2CHandle->RxLen--;
	}

	if(pI2CHandle->RxSize >1)
	{
		if(pI2CHandle->RxLen==2)
		{
			//clear the ack bit
			pI2CHandle->pI2Cx->CR1	&= ~(1<<10);


			//read the dr
			pI2CHandle->pRxBuffer = (uint8_t*)pI2CHandle->pI2Cx->DR;
			pI2CHandle->pRxBuffer++;
			pI2CHandle->RxLen--;
		}


	}
	if(pI2CHandle->RxLen==0)
	{
		//close the i2c data reception and notify the application

		//1. generate the stop condition
		I2C_GenerateStopCondition(pI2CHandle->pI2Cx);

		//2.close the i2c rx
		I2C_CloseRecieveData(pI2CHandle);

		//3. notify the application
		I2C_ApplicationEventCallback(pI2CHandle, I2C_EV_RX_CMPLT);

	}
}
static void I2C_MasterHandleTXEInterrupt(I2C_Handle_t *pI2CHandle)
{
	//check for device mode
	if(pI2CHandle->pI2Cx->SR2&(0x1))
	{

		if(pI2CHandle->TxLen >0)
		{
			//1. load the data in dr
			pI2CHandle->pI2Cx->DR =	*(pI2CHandle->pTxBuffer);

			//2. decrement the tx len
			pI2CHandle->TxLen--;

			//3. increment the buffer addr
			pI2CHandle->pTxBuffer++;
		}
	}
}

void I2C_CloseSendData(I2C_Handle_t *pI2CHandle)
{
	pI2CHandle->pTxBuffer = NULL;
	pI2CHandle->TxLen = 0;
	pI2CHandle->TxRxState = I2C_READY;




	//Implement the code to DISABLE ITBUFEN Control Bit
	pI2CHandle->pI2Cx->CR2 &= ~( 1 << 10);

	//Implement the code to DISABLE ITEVFEN Control Bit
	pI2CHandle->pI2Cx->CR2 &= ~( 1 << 9);


}


void I2C_CloseRecieveData(I2C_Handle_t *pI2CHandle)
{
	pI2CHandle->pRxBuffer = NULL;
	pI2CHandle->RxLen = 0;
	pI2CHandle->TxRxState = I2C_READY;
	pI2CHandle->RxSize = 0; //Rxsize is used in the ISR code to manage the data reception





	//Implement the code to enable ITBUFEN Control Bit
	pI2CHandle->pI2Cx->CR2 &= ~( 1 << 10);


	//Implement the code to enable ITEVFEN Control Bit
	pI2CHandle->pI2Cx->CR2 &= ~( 1 << 9);
	// re- enable acking
	pI2CHandle->pI2Cx->CR1	|= (1<<10);

}






/*********************************************************************
 * @fn      		  - I2C_ER_IRQHandling
 *
 * @brief             -
 *
 * @param[in]         -
 * @param[in]         -
 * @param[in]         -
 *
 * @return            -
 *
 * @Note              - Complete the code also define these macros in the driver
						header file
						#define I2C_ERROR_BERR  3
						#define I2C_ERROR_ARLO  4
						#define I2C_ERROR_AF    5
						#define I2C_ERROR_OVR   6
						#define I2C_ERROR_TIMEOUT 7

 */

void I2C_ER_IRQHandling(I2C_Handle_t *pI2CHandle)
{

	uint32_t temp1,temp2;

    //Know the status of  ITERREN control bit in the CR2
	temp2 = (pI2CHandle->pI2Cx->CR2) & ( 1 << 8);


/***********************Check for Bus error************************************/
	temp1 = (pI2CHandle->pI2Cx->SR1) & ( 1<< 8);
	if(temp1  && temp2 )
	{
		//This is Bus error

		//Implement the code to clear the buss error flag
		pI2CHandle->pI2Cx->SR1 &= ~( 1 << 8);

		//Implement the code to notify the application about the error
	   I2C_ApplicationEventCallback(pI2CHandle,I2C_ERROR_BERR);
	}

/***********************Check for arbitration lost error************************************/
	temp1 = (pI2CHandle->pI2Cx->SR1) & ( 1 << 9 );
	if(temp1  && temp2)
	{
		//This is arbitration lost error
		//Implement the code to clear the arbitration lost error flag
		pI2CHandle->pI2Cx->SR1 &= ~( 1 << 9);

		//Implement the code to notify the application about the error
		I2C_ApplicationEventCallback(pI2CHandle,I2C_ERROR_ARLO);

	}

/***********************Check for ACK failure  error************************************/

	temp1 = (pI2CHandle->pI2Cx->SR1) & ( 1 << 10);
	if(temp1  && temp2)
	{
		//This is ACK failure error

	    //Implement the code to clear the ACK failure error flag
		pI2CHandle->pI2Cx->SR1 &= ~( 1 << 10);
		//Implement the code to notify the application about the error
		I2C_ApplicationEventCallback(pI2CHandle,I2C_ERROR_AF);
	}

/***********************Check for Overrun/underrun error************************************/
	temp1 = (pI2CHandle->pI2Cx->SR1) & ( 1<<11);
	if(temp1  && temp2)
	{
		//This is Overrun/underrun

	    //Implement the code to clear the Overrun/underrun error flag
		pI2CHandle->pI2Cx->SR1 &= ~( 1 << 11);

		//Implement the code to notify the application about the error
		I2C_ApplicationEventCallback(pI2CHandle,I2C_ERROR_OVR);

	}

/***********************Check for Time out error************************************/
	temp1 = (pI2CHandle->pI2Cx->SR1) & ( 1 << 14);
	if(temp1  && temp2)
	{
		//This is Time out error

	    //Implement the code to clear the Time out error flag
		pI2CHandle->pI2Cx->SR1 &= ~( 1 << 14);
		//Implement the code to notify the application about the error
		I2C_ApplicationEventCallback(pI2CHandle,I2C_ERROR_TIMEOUT);
	}

}

